name: NekoRay Builder
description: Build NekoRay and push new PKGBUILD to AUR

branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  deploy_key:
    description: 'SSH private key for AUR'
    required: true
    default: ${{ secrets.DEPLOY_KEY }}
  package_name:
    description: 'Package name'
    required: true
    default: '${{ github.repository }}'